/**
 * @file position_limits.cpp
 * @brief Implementation of Position Limits Manager
 */

#include "risk/position_limits.hpp"
#include "core/logger.hpp"

#include <fstream>
#include <sstream>
#include <algorithm>
#include <cmath>

// Forward declaration for YAML parsing (will use yaml-cpp)
namespace YAML {
    class Node;
}

namespace hft::risk {

// ============================================================================
// PositionLimits Implementation
// ============================================================================

PositionLimits::PositionLimits() {
    // Set default limits
    defaultSymbolLimit_.limit = 1000000.0;
    defaultSymbolLimit_.type = LimitType::Notional;
    defaultSymbolLimit_.warningThreshold = 0.8;
    defaultSymbolLimit_.enabled = true;

    defaultExchangeLimit_.limit = 5000000.0;
    defaultExchangeLimit_.type = LimitType::Notional;
    defaultExchangeLimit_.warningThreshold = 0.8;
    defaultExchangeLimit_.maxPositionValue = 5000000.0;
    defaultExchangeLimit_.maxOpenOrders = 100;
    defaultExchangeLimit_.enabled = true;

    LOG_INFO("PositionLimits initialized with default limits");
}

PositionLimits::PositionLimits(std::shared_ptr<PositionManager> positionManager)
    : PositionLimits()
{
    positionManager_ = std::move(positionManager);
}

PositionLimits::~PositionLimits() = default;

bool PositionLimits::loadFromYaml(const std::filesystem::path& configPath) {
    try {
        std::ifstream file(configPath);
        if (!file.is_open()) {
            LOG_ERROR("Failed to open config file: {}", configPath.string());
            return false;
        }

        std::stringstream buffer;
        buffer << file.rdbuf();
        return loadFromYamlString(buffer.str());

    } catch (const std::exception& e) {
        LOG_ERROR("Failed to load YAML config: {}", e.what());
        return false;
    }
}

bool PositionLimits::saveToYaml(const std::filesystem::path& configPath) const {
    try {
        std::ofstream file(configPath);
        if (!file.is_open()) {
            LOG_ERROR("Failed to open config file for writing: {}", configPath.string());
            return false;
        }

        std::shared_lock lock(mutex_);

        file << "# Position Limits Configuration\n";
        file << "# Generated by HFT Position Limits Manager\n\n";

        // Portfolio limits
        file << "portfolio:\n";
        file << "  max_total_position_value: " << portfolioLimits_.maxTotalPositionValue << "\n";
        file << "  max_gross_exposure: " << portfolioLimits_.maxGrossExposure << "\n";
        file << "  max_net_exposure: " << portfolioLimits_.maxNetExposure << "\n";
        file << "  max_leverage: " << portfolioLimits_.maxLeverage << "\n";
        file << "  max_open_positions: " << portfolioLimits_.maxOpenPositions << "\n";
        file << "  max_concentration_pct: " << portfolioLimits_.maxConcentrationPct << "\n\n";

        // Symbol limits
        file << "symbols:\n";
        for (const auto& [symbol, limit] : symbolLimits_) {
            file << "  " << symbol << ":\n";
            file << "    limit: " << limit.limit << "\n";
            file << "    type: " << (limit.type == LimitType::Notional ? "notional" :
                                     limit.type == LimitType::Quantity ? "quantity" : "percentage") << "\n";
            file << "    warning_threshold: " << limit.warningThreshold << "\n";
            file << "    enabled: " << (limit.enabled ? "true" : "false") << "\n";
            if (limit.maxLongQuantity) {
                file << "    max_long_quantity: " << *limit.maxLongQuantity << "\n";
            }
            if (limit.maxShortQuantity) {
                file << "    max_short_quantity: " << *limit.maxShortQuantity << "\n";
            }
            if (limit.maxNotional) {
                file << "    max_notional: " << *limit.maxNotional << "\n";
            }
        }
        file << "\n";

        // Exchange limits
        file << "exchanges:\n";
        for (const auto& [exchange, limit] : exchangeLimits_) {
            file << "  " << exchange_to_string(exchange) << ":\n";
            file << "    max_position_value: " << limit.maxPositionValue << "\n";
            file << "    max_open_orders: " << limit.maxOpenOrders << "\n";
            file << "    enabled: " << (limit.enabled ? "true" : "false") << "\n";
            if (!limit.blockedSymbols.empty()) {
                file << "    blocked_symbols: [";
                for (size_t i = 0; i < limit.blockedSymbols.size(); ++i) {
                    if (i > 0) file << ", ";
                    file << limit.blockedSymbols[i];
                }
                file << "]\n";
            }
        }

        LOG_INFO("Saved position limits to: {}", configPath.string());
        return true;

    } catch (const std::exception& e) {
        LOG_ERROR("Failed to save YAML config: {}", e.what());
        return false;
    }
}

bool PositionLimits::loadFromYamlString(const std::string& yamlContent) {
    // Simple YAML-like parsing without external dependency
    // In production, use yaml-cpp for proper parsing
    try {
        std::unique_lock lock(mutex_);

        std::istringstream stream(yamlContent);
        std::string line;
        std::string currentSection;
        std::string currentItem;

        while (std::getline(stream, line)) {
            // Skip comments and empty lines
            size_t commentPos = line.find('#');
            if (commentPos != std::string::npos) {
                line = line.substr(0, commentPos);
            }

            // Trim whitespace
            size_t start = line.find_first_not_of(" \t");
            if (start == std::string::npos) continue;
            line = line.substr(start);

            if (line.empty()) continue;

            // Detect sections
            if (line == "portfolio:") {
                currentSection = "portfolio";
                continue;
            } else if (line == "symbols:") {
                currentSection = "symbols";
                continue;
            } else if (line == "exchanges:") {
                currentSection = "exchanges";
                continue;
            }

            // Parse key-value pairs
            size_t colonPos = line.find(':');
            if (colonPos != std::string::npos) {
                std::string key = line.substr(0, colonPos);
                std::string value = (colonPos + 1 < line.size()) ?
                    line.substr(colonPos + 1) : "";

                // Trim key and value
                size_t keyEnd = key.find_last_not_of(" \t");
                if (keyEnd != std::string::npos) key = key.substr(0, keyEnd + 1);

                size_t valStart = value.find_first_not_of(" \t");
                if (valStart != std::string::npos) value = value.substr(valStart);

                // Handle indented keys (section items)
                size_t indent = line.find_first_not_of(" \t");

                if (currentSection == "portfolio") {
                    if (key == "max_total_position_value") {
                        portfolioLimits_.maxTotalPositionValue = std::stod(value);
                    } else if (key == "max_gross_exposure") {
                        portfolioLimits_.maxGrossExposure = std::stod(value);
                    } else if (key == "max_net_exposure") {
                        portfolioLimits_.maxNetExposure = std::stod(value);
                    } else if (key == "max_leverage") {
                        portfolioLimits_.maxLeverage = std::stod(value);
                    } else if (key == "max_open_positions") {
                        portfolioLimits_.maxOpenPositions = std::stoull(value);
                    } else if (key == "max_concentration_pct") {
                        portfolioLimits_.maxConcentrationPct = std::stod(value);
                    }
                }
                // Additional parsing for symbols and exchanges would go here
            }
        }

        LOG_INFO("Loaded position limits from YAML");
        return true;

    } catch (const std::exception& e) {
        LOG_ERROR("Failed to parse YAML: {}", e.what());
        return false;
    }
}

void PositionLimits::setSymbolLimit(const Symbol& symbol, const SymbolPositionLimit& limit) {
    std::unique_lock lock(mutex_);
    symbolLimits_[std::string(symbol.view())] = limit;
    LOG_INFO("Set symbol limit: {} = {}", symbol.view(), limit.limit);
}

std::optional<SymbolPositionLimit> PositionLimits::getSymbolLimit(const Symbol& symbol) const {
    std::shared_lock lock(mutex_);

    auto it = symbolLimits_.find(std::string(symbol.view()));
    if (it != symbolLimits_.end()) {
        return it->second;
    }
    return std::nullopt;
}

void PositionLimits::removeSymbolLimit(const Symbol& symbol) {
    std::unique_lock lock(mutex_);
    symbolLimits_.erase(std::string(symbol.view()));
    LOG_INFO("Removed symbol limit: {}", symbol.view());
}

std::vector<SymbolPositionLimit> PositionLimits::getAllSymbolLimits() const {
    std::shared_lock lock(mutex_);

    std::vector<SymbolPositionLimit> result;
    result.reserve(symbolLimits_.size());

    for (const auto& [symbol, limit] : symbolLimits_) {
        result.push_back(limit);
    }

    return result;
}

void PositionLimits::setExchangeLimit(Exchange exchange, const ExchangePositionLimit& limit) {
    std::unique_lock lock(mutex_);
    exchangeLimits_[exchange] = limit;
    LOG_INFO("Set exchange limit: {} = {}", exchange_to_string(exchange), limit.maxPositionValue);
}

std::optional<ExchangePositionLimit> PositionLimits::getExchangeLimit(Exchange exchange) const {
    std::shared_lock lock(mutex_);

    auto it = exchangeLimits_.find(exchange);
    if (it != exchangeLimits_.end()) {
        return it->second;
    }
    return std::nullopt;
}

void PositionLimits::removeExchangeLimit(Exchange exchange) {
    std::unique_lock lock(mutex_);
    exchangeLimits_.erase(exchange);
    LOG_INFO("Removed exchange limit: {}", exchange_to_string(exchange));
}

std::vector<ExchangePositionLimit> PositionLimits::getAllExchangeLimits() const {
    std::shared_lock lock(mutex_);

    std::vector<ExchangePositionLimit> result;
    result.reserve(exchangeLimits_.size());

    for (const auto& [exchange, limit] : exchangeLimits_) {
        result.push_back(limit);
    }

    return result;
}

void PositionLimits::setPortfolioLimits(const PortfolioLimits& limits) {
    std::unique_lock lock(mutex_);
    portfolioLimits_ = limits;
    LOG_INFO("Set portfolio limits: maxTotal={}", limits.maxTotalPositionValue);
}

const PortfolioLimits& PositionLimits::getPortfolioLimits() const {
    std::shared_lock lock(mutex_);
    return portfolioLimits_;
}

LimitCheckResult PositionLimits::checkSymbolLimit(
    const Symbol& symbol,
    double newQuantity,
    double price
) const {
    std::shared_lock lock(mutex_);

    LimitCheckResult result;
    result.passed = true;
    result.limitName = std::string(symbol.view()) + "_position";

    // Get limit for symbol (or use default)
    SymbolPositionLimit limit = defaultSymbolLimit_;
    auto it = symbolLimits_.find(std::string(symbol.view()));
    if (it != symbolLimits_.end()) {
        limit = it->second;
    }

    if (!limit.enabled) {
        return result; // Limit disabled, always pass
    }

    // Get current position value
    double currentValue = getCurrentSymbolValue(symbol);
    double newValue = std::abs(newQuantity) * price;

    // Check based on limit type
    switch (limit.type) {
        case LimitType::Notional:
            result.currentValue = currentValue + newValue;
            result.limitValue = limit.maxNotional.value_or(limit.limit);
            break;

        case LimitType::Quantity:
            result.currentValue = std::abs(newQuantity);
            result.limitValue = limit.limit;
            break;

        case LimitType::Percentage:
            {
                double totalValue = getCurrentPortfolioValue();
                result.currentValue = totalValue > 0 ?
                    ((currentValue + newValue) / totalValue) * 100.0 : 0.0;
                result.limitValue = limit.maxConcentrationPct.value_or(limit.limit);
            }
            break;
    }

    result.utilizationPct = result.limitValue > 0 ?
        (result.currentValue / result.limitValue) * 100.0 : 0.0;

    if (result.currentValue > result.limitValue) {
        result.passed = false;
        result.message = "Symbol position limit exceeded";
    } else if (result.currentValue > limit.getWarningLevel()) {
        result.message = "Symbol position approaching limit";
    }

    return result;
}

LimitCheckResult PositionLimits::checkExchangeLimit(
    Exchange exchange,
    double additionalValue
) const {
    std::shared_lock lock(mutex_);

    LimitCheckResult result;
    result.passed = true;
    result.limitName = std::string(exchange_to_string(exchange)) + "_position";

    // Get limit for exchange (or use default)
    ExchangePositionLimit limit = defaultExchangeLimit_;
    auto it = exchangeLimits_.find(exchange);
    if (it != exchangeLimits_.end()) {
        limit = it->second;
    }

    if (!limit.enabled) {
        return result;
    }

    double currentValue = getCurrentExchangeValue(exchange);
    result.currentValue = currentValue + additionalValue;
    result.limitValue = limit.maxPositionValue;
    result.utilizationPct = result.limitValue > 0 ?
        (result.currentValue / result.limitValue) * 100.0 : 0.0;

    if (result.currentValue > result.limitValue) {
        result.passed = false;
        result.message = "Exchange position limit exceeded";
    } else if (result.currentValue > limit.getWarningLevel()) {
        result.message = "Exchange position approaching limit";
    }

    return result;
}

LimitCheckResult PositionLimits::checkPortfolioLimits(double additionalValue) const {
    std::shared_lock lock(mutex_);

    LimitCheckResult result;
    result.passed = true;
    result.limitName = "portfolio_total";

    double currentValue = getCurrentPortfolioValue();
    result.currentValue = currentValue + additionalValue;
    result.limitValue = portfolioLimits_.maxTotalPositionValue;
    result.utilizationPct = result.limitValue > 0 ?
        (result.currentValue / result.limitValue) * 100.0 : 0.0;

    if (result.currentValue > result.limitValue) {
        result.passed = false;
        result.message = "Portfolio position limit exceeded";
    }

    // Check open positions count
    if (positionManager_) {
        size_t openCount = positionManager_->getOpenPositionCount();
        if (openCount >= portfolioLimits_.maxOpenPositions) {
            result.passed = false;
            result.message = "Maximum open positions reached";
        }
    }

    return result;
}

std::vector<LimitCheckResult> PositionLimits::checkAllLimits(
    const Symbol& symbol,
    Exchange exchange,
    Side side,
    double quantity,
    double price
) const {
    std::vector<LimitCheckResult> results;

    double notional = quantity * price;

    // Check symbol limit
    results.push_back(checkSymbolLimit(symbol, quantity, price));

    // Check exchange limit
    results.push_back(checkExchangeLimit(exchange, notional));

    // Check portfolio limits
    results.push_back(checkPortfolioLimits(notional));

    // Check if symbol is allowed on exchange
    if (!isSymbolAllowedOnExchange(symbol, exchange)) {
        LimitCheckResult result;
        result.passed = false;
        result.limitName = "symbol_exchange_allowed";
        result.message = "Symbol not allowed on this exchange";
        results.push_back(result);
    }

    return results;
}

bool PositionLimits::isSymbolAllowedOnExchange(const Symbol& symbol, Exchange exchange) const {
    std::shared_lock lock(mutex_);

    auto it = exchangeLimits_.find(exchange);
    if (it == exchangeLimits_.end()) {
        return true; // No limit configured, allow all
    }

    const auto& limit = it->second;
    std::string symbolStr(symbol.view());

    // Check blocked list
    if (std::find(limit.blockedSymbols.begin(), limit.blockedSymbols.end(),
                  symbolStr) != limit.blockedSymbols.end()) {
        return false;
    }

    // Check allowed list (empty = all allowed)
    if (!limit.allowedSymbols.empty()) {
        return std::find(limit.allowedSymbols.begin(), limit.allowedSymbols.end(),
                         symbolStr) != limit.allowedSymbols.end();
    }

    return true;
}

double PositionLimits::getSymbolUtilization(const Symbol& symbol) const {
    std::shared_lock lock(mutex_);

    double currentValue = getCurrentSymbolValue(symbol);

    SymbolPositionLimit limit = defaultSymbolLimit_;
    auto it = symbolLimits_.find(std::string(symbol.view()));
    if (it != symbolLimits_.end()) {
        limit = it->second;
    }

    return limit.limit > 0 ? (currentValue / limit.limit) * 100.0 : 0.0;
}

double PositionLimits::getExchangeUtilization(Exchange exchange) const {
    std::shared_lock lock(mutex_);

    double currentValue = getCurrentExchangeValue(exchange);

    ExchangePositionLimit limit = defaultExchangeLimit_;
    auto it = exchangeLimits_.find(exchange);
    if (it != exchangeLimits_.end()) {
        limit = it->second;
    }

    return limit.maxPositionValue > 0 ?
        (currentValue / limit.maxPositionValue) * 100.0 : 0.0;
}

double PositionLimits::getPortfolioUtilization() const {
    std::shared_lock lock(mutex_);

    double currentValue = getCurrentPortfolioValue();
    return portfolioLimits_.maxTotalPositionValue > 0 ?
        (currentValue / portfolioLimits_.maxTotalPositionValue) * 100.0 : 0.0;
}

std::unordered_map<std::string, double> PositionLimits::getAllUtilizations() const {
    std::unordered_map<std::string, double> utilizations;

    utilizations["portfolio"] = getPortfolioUtilization();

    for (const auto& [symbol, limit] : symbolLimits_) {
        utilizations["symbol_" + symbol] = getSymbolUtilization(Symbol(symbol));
    }

    for (const auto& [exchange, limit] : exchangeLimits_) {
        utilizations["exchange_" + std::string(exchange_to_string(exchange))] =
            getExchangeUtilization(exchange);
    }

    return utilizations;
}

double PositionLimits::getSymbolHeadroom(const Symbol& symbol, Side side) const {
    std::shared_lock lock(mutex_);

    double currentValue = getCurrentSymbolValue(symbol);

    SymbolPositionLimit limit = defaultSymbolLimit_;
    auto it = symbolLimits_.find(std::string(symbol.view()));
    if (it != symbolLimits_.end()) {
        limit = it->second;
    }

    return std::max(0.0, limit.limit - currentValue);
}

double PositionLimits::getExchangeHeadroom(Exchange exchange) const {
    std::shared_lock lock(mutex_);

    double currentValue = getCurrentExchangeValue(exchange);

    ExchangePositionLimit limit = defaultExchangeLimit_;
    auto it = exchangeLimits_.find(exchange);
    if (it != exchangeLimits_.end()) {
        limit = it->second;
    }

    return std::max(0.0, limit.maxPositionValue - currentValue);
}

double PositionLimits::getPortfolioHeadroom() const {
    std::shared_lock lock(mutex_);

    double currentValue = getCurrentPortfolioValue();
    return std::max(0.0, portfolioLimits_.maxTotalPositionValue - currentValue);
}

void PositionLimits::setPositionManager(std::shared_ptr<PositionManager> positionManager) {
    positionManager_ = std::move(positionManager);
}

std::shared_ptr<PositionManager> PositionLimits::getPositionManager() const {
    return positionManager_;
}

double PositionLimits::getCurrentSymbolValue(const Symbol& symbol) const {
    if (!positionManager_) return 0.0;

    auto positions = positionManager_->getPositionsForSymbol(symbol);
    double total = 0.0;
    for (const auto& pos : positions) {
        total += pos.notionalValue();
    }
    return total;
}

double PositionLimits::getCurrentExchangeValue(Exchange exchange) const {
    if (!positionManager_) return 0.0;

    auto positions = positionManager_->getPositionsForExchange(exchange);
    double total = 0.0;
    for (const auto& pos : positions) {
        total += pos.notionalValue();
    }
    return total;
}

double PositionLimits::getCurrentPortfolioValue() const {
    if (!positionManager_) return 0.0;
    return positionManager_->getGrossExposure();
}

// ============================================================================
// PositionLimitsBuilder Implementation
// ============================================================================

PositionLimitsBuilder& PositionLimitsBuilder::withPositionManager(
    std::shared_ptr<PositionManager> pm) {
    positionManager_ = std::move(pm);
    return *this;
}

PositionLimitsBuilder& PositionLimitsBuilder::withSymbolLimit(
    const Symbol& symbol, double maxNotional) {
    SymbolPositionLimit limit;
    limit.symbol = symbol;
    limit.limit = maxNotional;
    limit.maxNotional = maxNotional;
    limit.type = LimitType::Notional;
    limit.enabled = true;
    symbolLimits_.emplace_back(symbol, limit);
    return *this;
}

PositionLimitsBuilder& PositionLimitsBuilder::withExchangeLimit(
    Exchange exchange, double maxValue) {
    ExchangePositionLimit limit;
    limit.exchange = exchange;
    limit.maxPositionValue = maxValue;
    limit.limit = maxValue;
    limit.type = LimitType::Notional;
    limit.enabled = true;
    exchangeLimits_.emplace_back(exchange, limit);
    return *this;
}

PositionLimitsBuilder& PositionLimitsBuilder::withPortfolioLimits(
    const PortfolioLimits& limits) {
    portfolioLimits_ = limits;
    return *this;
}

PositionLimitsBuilder& PositionLimitsBuilder::loadFromYaml(
    const std::filesystem::path& path) {
    yamlPath_ = path;
    return *this;
}

std::unique_ptr<PositionLimits> PositionLimitsBuilder::build() {
    auto limits = std::make_unique<PositionLimits>(positionManager_);

    limits->setPortfolioLimits(portfolioLimits_);

    for (const auto& [symbol, limit] : symbolLimits_) {
        limits->setSymbolLimit(symbol, limit);
    }

    for (const auto& [exchange, limit] : exchangeLimits_) {
        limits->setExchangeLimit(exchange, limit);
    }

    if (yamlPath_) {
        limits->loadFromYaml(*yamlPath_);
    }

    return limits;
}

} // namespace hft::risk
